services:
  backend_soon:
    build: .
    container_name: backend_soon
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - share_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scr_histograma_backend.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.scr_histograma_backend.entrypoints=websecure"
      - "traefik.http.routers.scr_histograma_backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.scr_histograma_backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.secure-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.scr_histograma_backend.middlewares=secure-headers"

networks:
  share_network:
    external: true
