services:
  backend_soon:
    build: .
    container_name: backend_soon
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - share_network
      - backend_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scr_histograma_backend.rule=Host(`${TRAEFIK_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.scr_histograma_backend.entrypoints=websecure"
      - "traefik.http.routers.scr_histograma_backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.scr_histograma_backend.loadbalancer.server.port=3000"

  # postgres:
  #   image: postgres:18.4
  #   container_name: postgresql
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_PASSWORD=${PG_PASS}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql
  #   networks:
  #     - backend_net

  redis:
    image: redis:8.8.0
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    env_file:
      - .env
    command: redis-server --requirepass ${RDS_PASS}
    volumes:
      - redis_data:/data
    networks:
      - backend_net

volumes:
  redis_data:
  # postgres_data:

networks:
  backend_net:
    external: false
  share_network:
    external: true
